"use client";

import { useMemo, useState, useRef, useEffect } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { buildPaymentLinkUrl, generateLinkId } from "@/lib/paymentLink";
import { Plus, Copy, Check, Lock, X, Info, Share2, Image, Palette } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import NextImage from "next/image";
import BlinkCard from "@/components/BlinkCard";

export default function CreatePage() {
  const { publicKey } = useWallet();
  const [requestedAmount, setRequestedAmount] = useState<string>("0.1");
  const [linkId, setLinkId] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [activeMode, setActiveMode] = useState<'plink' | 'blink'>('plink');
  const [showHowItWorks, setShowHowItWorks] = useState(false);
  const [selectedImage, setSelectedImage] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [customMessage, setCustomMessage] = useState<string>("");

  // Blink card customization
  const [cardTitle, setCardTitle] = useState<string>("Support My Work");
  const [cardDescription, setCardDescription] = useState<string>("Your contribution helps me create amazing content!");
  const [cardImageUrl, setCardImageUrl] = useState<string>("");
  const [cardType, setCardType] = useState<'tip' | 'donation' | 'payment' | 'custom'>('tip');
  const [primaryColor, setPrimaryColor] = useState<string>("#7C3AED");
  const [secondaryColor, setSecondaryColor] = useState<string>("#14F195");
  const [textColor, setTextColor] = useState<string>("#FFFFFF");
  const [savingCard, setSavingCard] = useState(false);
  const [generatingImage, setGeneratingImage] = useState(false);
  const [isAutoGeneratedImage, setIsAutoGeneratedImage] = useState(false);

  // Ref for the requesting card element
  const requestingCardRef = useRef<HTMLDivElement>(null);

  const link = useMemo(() => {
    if (!linkId) return null;
    if (typeof window === "undefined") return null;
    return buildPaymentLinkUrl(window.location.origin, {
      requestedAmount,
      linkId
    });
  }, [linkId, requestedAmount]);

  const handleCopy = async () => {
    if (link) {
      await navigator.clipboard.writeText(link);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleImageSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file && file.type.startsWith('image/')) {
      setSelectedImage(file);
      setIsAutoGeneratedImage(false); // User uploaded custom image
      const reader = new FileReader();
      reader.onloadend = () => {
        setImagePreview(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const saveBlinkCard = async (generatedLinkId: string) => {
    if (activeMode !== 'blink') return;

    setSavingCard(true);
    try {
      const response = await fetch('/api/blink/save', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          linkId: generatedLinkId,
          requestedAmount,
          cardTitle,
          cardDescription,
          cardImageUrl,
          cardType,
          primaryColor,
          secondaryColor,
          textColor,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to save blink card');
      }
    } catch (error) {
      console.error('Error saving blink card:', error);
    } finally {
      setSavingCard(false);
    }
  };

  // Generate card image using pure Canvas API (avoids oklch color issues with html2canvas)
  const generateCardImage = async () => {
    setGeneratingImage(true);
    try {
      const width = 640;
      const height = activeMode === 'blink' ? 480 : 360;
      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');

      if (!ctx) {
        throw new Error('Could not get canvas context');
      }

      // Use card colors for blink, or default purple/green for plink
      const primary = activeMode === 'blink' ? primaryColor : '#7C3AED';
      const secondary = activeMode === 'blink' ? secondaryColor : '#14F195';
      const text = activeMode === 'blink' ? textColor : '#FFFFFF';

      // Background gradient
      const bgGradient = ctx.createLinearGradient(0, 0, width, height);
      bgGradient.addColorStop(0, primary);
      bgGradient.addColorStop(0.5, primary + 'dd');
      bgGradient.addColorStop(1, secondary + '44');

      // Draw rounded rectangle background
      const radius = 32;
      ctx.beginPath();
      ctx.moveTo(radius, 0);
      ctx.lineTo(width - radius, 0);
      ctx.quadraticCurveTo(width, 0, width, radius);
      ctx.lineTo(width, height - radius);
      ctx.quadraticCurveTo(width, height, width - radius, height);
      ctx.lineTo(radius, height);
      ctx.quadraticCurveTo(0, height, 0, height - radius);
      ctx.lineTo(0, radius);
      ctx.quadraticCurveTo(0, 0, radius, 0);
      ctx.closePath();
      ctx.fillStyle = bgGradient;
      ctx.fill();

      // Glow effects
      const glow1 = ctx.createRadialGradient(0, 80, 0, 0, 80, 120);
      glow1.addColorStop(0, secondary + '80');
      glow1.addColorStop(1, secondary + '00');
      ctx.fillStyle = glow1;
      ctx.fillRect(0, 0, 200, 200);

      const glow2 = ctx.createRadialGradient(width, height - 80, 0, width, height - 80, 150);
      glow2.addColorStop(0, primary + '60');
      glow2.addColorStop(1, primary + '00');
      ctx.fillStyle = glow2;
      ctx.fillRect(width - 250, height - 250, 250, 250);

      if (activeMode === 'blink') {
        // Blink card layout
        const typeEmoji = cardType === 'tip' ? '💰' : cardType === 'donation' ? '❤️' : cardType === 'payment' ? '💳' : '✨';
        const typeLabel = cardType.charAt(0).toUpperCase() + cardType.slice(1);

        // Type badge
        ctx.fillStyle = text + '44';
        ctx.beginPath();
        ctx.roundRect(40, 40, 120, 36, 18);
        ctx.fill();
        ctx.fillStyle = text;
        ctx.font = 'bold 14px system-ui';
        ctx.textAlign = 'left';
        ctx.fillText(`${typeEmoji} ${typeLabel}`, 55, 64);

        // Title
        ctx.fillStyle = text;
        ctx.font = 'bold 28px system-ui';
        ctx.textAlign = 'left';
        ctx.fillText(cardTitle.slice(0, 30), 40, 120);

        // Description
        ctx.fillStyle = text + 'cc';
        ctx.font = '16px system-ui';
        const desc = cardDescription.slice(0, 80) + (cardDescription.length > 80 ? '...' : '');
        ctx.fillText(desc, 40, 155);

        // Amount box
        ctx.fillStyle = text + '22';
        ctx.beginPath();
        ctx.roundRect(40, 190, width - 80, 100, 16);
        ctx.fill();

        ctx.fillStyle = text + 'aa';
        ctx.font = 'bold 12px system-ui';
        ctx.fillText('AMOUNT', 60, 220);

        ctx.fillStyle = text;
        ctx.font = 'bold 48px system-ui';
        ctx.shadowColor = secondary + '88';
        ctx.shadowBlur = 15;
        ctx.fillText(requestedAmount, 60, 270);
        ctx.shadowBlur = 0;

        ctx.fillStyle = text + 'aa';
        ctx.font = 'bold 24px system-ui';
        // Measure amount width using the 48px font
        ctx.save();
        ctx.font = 'bold 48px system-ui';
        const amountWidth = ctx.measureText(requestedAmount).width;
        ctx.restore();
        ctx.font = 'bold 24px system-ui';
        ctx.fillText('SOL', 60 + amountWidth + 15, 270);

        // Footer
        ctx.fillStyle = text + '66';
        ctx.font = '12px system-ui';
        ctx.textAlign = 'center';
        ctx.fillText('POWERED BY Privacy Cash', width / 2, height - 30);
      } else {
        // P-Link layout (Requesting card)
        ctx.fillStyle = '#9ca3af';
        ctx.font = '600 16px monospace';
        ctx.textAlign = 'center';
        ctx.fillText('REQUESTING', width / 2, 100);

        ctx.fillStyle = '#ffffff';
        ctx.font = 'bold 72px system-ui';
        ctx.shadowColor = 'rgba(19, 241, 149, 0.5)';
        ctx.shadowBlur = 20;
        ctx.fillText(requestedAmount, width / 2 - 40, 200);
        ctx.shadowBlur = 0;

        ctx.fillStyle = '#13f195';
        ctx.font = 'bold 36px system-ui';
        ctx.shadowColor = 'rgba(19, 241, 149, 0.6)';
        ctx.shadowBlur = 15;
        ctx.fillText('SOL', width / 2 + 60, 200);
        ctx.shadowBlur = 0;

        ctx.fillStyle = '#6b7280';
        ctx.font = '14px monospace';
        ctx.fillText(`≈ $${(parseFloat(requestedAmount || '0') * 150).toFixed(2)} USD`, width / 2, 250);

        ctx.fillStyle = 'rgba(255, 255, 255, 0.3)';
        ctx.font = '12px system-ui';
        ctx.fillText('Privacy Cash', width / 2, height - 30);
      }

      canvas.toBlob((blob) => {
        if (blob) {
          const file = new File([blob], 'payment-card.png', { type: 'image/png' });
          setSelectedImage(file);
          setImagePreview(canvas.toDataURL('image/png'));
          setIsAutoGeneratedImage(true);
        }
      }, 'image/png');
    } catch (error) {
      console.error('Error generating card image:', error);
    } finally {
      setGeneratingImage(false);
    }
  };

  // Auto-generate card image when dialog opens (for both P-link and B-link)
  useEffect(() => {
    if (link && !selectedImage) {
      // Small delay to ensure dialog is rendered
      const timer = setTimeout(() => {
        generateCardImage();
      }, 300);
      return () => clearTimeout(timer);
    }
  }, [link]);

  const handleShare = async () => {
    if (!link) return;

    // Get type-specific messaging for blink
    const getBlinkMessage = () => {
      switch (cardType) {
        case 'tip':
          return {
            emoji: '💰',
            title: 'Tip Request',
            action: 'Leave a tip',
            description: 'Show your appreciation with a tip!'
          };
        case 'donation':
          return {
            emoji: '❤️',
            title: 'Donation Request',
            action: 'Make a donation',
            description: 'Support a cause you care about!'
          };
        case 'payment':
          return {
            emoji: '💳',
            title: 'Payment Request',
            action: 'Complete payment',
            description: 'Quick and easy Solana payment!'
          };
        default:
          return {
            emoji: '✨',
            title: cardTitle || 'Payment Request',
            action: 'Send payment',
            description: cardDescription || 'Pay with Solana!'
          };
      }
    };

    const blinkInfo = getBlinkMessage();

    let paymentDetails: string;
    let defaultTitle: string;

    if (activeMode === 'blink') {
      paymentDetails = `${blinkInfo.emoji} ${blinkInfo.title}\n\n` +
        `� Amount: ${requestedAmount} SOL (≈$${(parseFloat(requestedAmount || '0') * 150).toFixed(2)} USD)\n\n` +
        `${blinkInfo.description}\n\n` +
        `⚡ ${blinkInfo.action} directly from social media with Solana Blinks!\n\n` +
        `🔗 Payment Link:\n${link}\n\n` +
        `✨ Create your own at Privacy Cash!`;
      defaultTitle = `${blinkInfo.emoji} ${blinkInfo.title}`;
    } else {
      paymentDetails = `💰 Amount: ${requestedAmount} SOL (≈$${(parseFloat(requestedAmount || '0') * 150).toFixed(2)} USD)\n\n` +
        `🔐 Zero-knowledge proof payment - your wallet stays private!\n\n` +
        `🔗 Payment Link:\n${link}\n\n` +
        `✨ Generate your own private payment links at Privacy Cash!`;
      defaultTitle = '🔒 Private Payment Request 🔒';
    }

    const messageText = customMessage
      ? `${customMessage}\n\n${paymentDetails}`
      : `${defaultTitle}\n\n${paymentDetails}`;

    const shareData: ShareData = {
      title: `${activeMode === 'plink' ? 'P-Link' : blinkInfo.title}`,
      text: messageText,
      // url: link,
    };

    // Add image if selected and supported
    if (selectedImage && navigator.canShare) {
      const filesArray = [selectedImage];
      if (navigator.canShare({ files: filesArray })) {
        shareData.files = filesArray;
      }
    }

    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        // Fallback to copy if share not supported
        await handleCopy();
      }
    } catch (err) {
      // User cancelled or error occurred
      console.log('Share cancelled or failed:', err);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.3 }}
      className="min-h-screen bg-white dark:bg-gray-950 text-black dark:text-white"
    >
      {/* Header */}
      <div className="flex items-center py-8 px-6 pb-4">
        <div className="flex items-center gap-2">
          <span className="text-neon-green">$</span>
          <h1 className="text-3xl font-bold text-black dark:text-white">Create Payment</h1>
        </div>
      </div>

      <main className="flex-1 w-full max-w-lg mx-auto flex flex-col px-6 pb-36">
        {/* Mode Toggle */}
        <div className="flex flex-col gap-1 pt-2 border-b border-gray-200 dark:border-gray-700 pb-4">
          <p className="text-neon-green font-mono tracking-widest uppercase mb-2 text-xs">
            Payment Type
          </p>
          <div className="flex gap-2 bg-gray-100 dark:bg-gray-800 rounded-xl p-1">
            <button
              onClick={() => setActiveMode('plink')}
              className={`flex-1 py-2.5 px-4 rounded-lg text-sm font-bold transition-all ${activeMode === 'plink'
                ? 'bg-neon-green text-black shadow-sm'
                : 'text-gray-500 dark:text-gray-400 hover:text-black dark:hover:text-white'
                }`}
            >
              <div className="flex items-center justify-center gap-2">
                <Lock size={16} />
                <span>P-Link</span>
              </div>
            </button>
            <button
              onClick={() => setActiveMode('blink')}
              className={`flex-1 py-2.5 px-4 rounded-lg text-sm font-bold transition-all ${activeMode === 'blink'
                ? 'bg-neon-green text-black shadow-sm'
                : 'text-gray-500 dark:text-gray-400 hover:text-black dark:hover:text-white'
                }`}
            >
              <div className="flex items-center justify-center gap-2">
                <Share2 size={16} />
                <span>Blink</span>
              </div>
            </button>
          </div>
          <button
            onClick={() => setShowHowItWorks(true)}
            className="mt-2 text-xs text-gray-500 dark:text-gray-400 hover:text-neon-green transition-colors flex items-center justify-center gap-1"
          >
            <Info size={12} />
            <span>How {activeMode === 'plink' ? 'P-Links' : 'Blinks'} work</span>
          </button>
        </div>

        {/* Amount Input Section */}
        <div className="flex flex-col items-center gap-6 py-6 mb-6 border rounded-2xl shadow-sm dark:shadow-gray-900 p-6 mt-6 border-gray-200 dark:border-gray-700">
          <div className="text-center w-full">
            <p className="text-sm font-medium text-gray-500 dark:text-gray-400 mb-2">I want to Request</p>
            <div className="flex items-center justify-center bg-gray-100 dark:bg-gray-800 w-52 mx-auto p-4 gap-3 rounded-2xl">
              <input
                type="text"
                inputMode="decimal"
                value={requestedAmount}
                onChange={(e) => setRequestedAmount(e.target.value)}
                className="text-4xl font-bold tracking-tight text-black dark:text-white bg-transparent border-none outline-none w-32 text-center"
                placeholder="0.1"
              />
              <span className="text-2xl font-bold text-gray-400">SOL</span>
            </div>
            <p className="text-xs text-gray-400 mt-2">≈ ${(parseFloat(requestedAmount || '0') * 150).toFixed(2)} USD</p>
          </div>

          {/* Info Cards */}
          <div className="flex justify-center gap-3 items-center text-center w-full pt-4 border-t border-gray-200 dark:border-gray-700">
            <div className="flex gap-2">
              <div className="text-xs items-center flex font-medium text-gray-500 dark:text-gray-400">
                {activeMode === 'plink' ? <p className="text-green-400">Privacy</p> : <p className="text-green-400">Platform</p>}
              </div>
              <div className="text-sm font-bold text-black dark:text-white">
                {activeMode === 'plink' ? <p>Zero-Knowledge</p> : <p>Social Media</p>}
              </div>
            </div>
            <p>|</p>
            <div className="flex gap-2">
              <p className="text-xs items-center flex font-medium text-gray-500 dark:text-purple-400">Network</p>
              <p className="text-sm font-bold text-black dark:text-white">Solana</p>
            </div>
          </div>
        </div>

        {/* Connected Wallet */}
        {publicKey && (
          <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl p-4 mb-6">
            <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-2">Connected Wallet</p>
            <p className="text-xs font-mono text-black dark:text-white break-all">{publicKey.toBase58()}</p>
          </div>
        )}

        {/* Blink Card Customization */}
        {activeMode === 'blink' && (
          <div className="space-y-6 mb-6">
            {/* Card Preview */}
            <div>
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-lg font-bold text-black dark:text-white flex items-center gap-2">
                  <Palette size={20} className="text-neon-green" />
                  Card Preview
                </h3>
              </div>
              <BlinkCard
                data={{
                  cardTitle,
                  cardDescription,
                  cardImageUrl,
                  cardType,
                  primaryColor,
                  secondaryColor,
                  textColor,
                  requestedAmount,
                }}
                animate={false}
              />
            </div>

            {/* Customization Panel */}
            <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-2xl p-5 space-y-5">
              <h3 className="text-base font-bold text-black dark:text-white">Customize Your Card</h3>

              {/* Card Type */}
              <div>
                <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 block">Card Type</label>
                <div className="grid grid-cols-4 gap-2">
                  {(['tip', 'donation', 'payment', 'custom'] as const).map((type) => (
                    <button
                      key={type}
                      onClick={() => setCardType(type)}
                      className={`py-2 px-3 rounded-lg text-sm font-bold transition-all ${cardType === type
                        ? 'bg-neon-green text-black shadow-sm'
                        : 'bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700'
                        }`}
                    >
                      {type === 'tip' && '💰'} {type === 'donation' && '❤️'} {type === 'payment' && '💳'} {type === 'custom' && '✨'}
                    </button>
                  ))}
                </div>
              </div>

              {/* Title */}
              <div>
                <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 block">Card Title</label>
                <input
                  type="text"
                  value={cardTitle}
                  onChange={(e) => setCardTitle(e.target.value)}
                  maxLength={100}
                  placeholder="e.g., Support My Work"
                  className="w-full bg-gray-50 dark:bg-gray-800 border-2 border-gray-200 dark:border-gray-700 rounded-xl px-4 py-3 text-sm text-black dark:text-white outline-none focus:border-neon-green transition-colors"
                />
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">{cardTitle.length}/100</p>
              </div>

              {/* Description */}
              <div>
                <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 block">Description</label>
                <textarea
                  value={cardDescription}
                  onChange={(e) => setCardDescription(e.target.value)}
                  maxLength={500}
                  rows={3}
                  placeholder="Tell people what this is for..."
                  className="w-full bg-gray-50 dark:bg-gray-800 border-2 border-gray-200 dark:border-gray-700 rounded-xl px-4 py-3 text-sm text-black dark:text-white outline-none focus:border-neon-green transition-colors resize-none"
                />
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">{cardDescription.length}/500</p>
              </div>

              {/* Image URL */}
              <div>
                <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 block">Image URL (Optional)</label>
                <input
                  type="text"
                  value={cardImageUrl}
                  onChange={(e) => setCardImageUrl(e.target.value)}
                  placeholder="https://example.com/image.jpg"
                  className="w-full bg-gray-50 dark:bg-gray-800 border-2 border-gray-200 dark:border-gray-700 rounded-xl px-4 py-3 text-sm text-black dark:text-white outline-none focus:border-neon-green transition-colors"
                />
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">Add an image to make your card more appealing</p>
              </div>

              {/* Colors */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div>
                  <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 block">Primary</label>
                  <div className="flex gap-2">
                    <input
                      type="color"
                      value={primaryColor}
                      onChange={(e) => setPrimaryColor(e.target.value)}
                      className="w-12 h-12 rounded-lg cursor-pointer border-2 border-gray-300 dark:border-gray-600 shrink-0"
                    />
                    <input
                      type="text"
                      value={primaryColor}
                      onChange={(e) => setPrimaryColor(e.target.value)}
                      className="flex-1 min-w-0 bg-gray-50 dark:bg-gray-800 border-2 border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 text-xs font-mono text-black dark:text-white outline-none focus:border-neon-green"
                    />
                  </div>
                </div>
                <div>
                  <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 block">Accent</label>
                  <div className="flex gap-2">
                    <input
                      type="color"
                      value={secondaryColor}
                      onChange={(e) => setSecondaryColor(e.target.value)}
                      className="w-12 h-12 rounded-lg cursor-pointer border-2 border-gray-300 dark:border-gray-600 shrink-0"
                    />
                    <input
                      type="text"
                      value={secondaryColor}
                      onChange={(e) => setSecondaryColor(e.target.value)}
                      className="flex-1 min-w-0 bg-gray-50 dark:bg-gray-800 border-2 border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 text-xs font-mono text-black dark:text-white outline-none focus:border-neon-green"
                    />
                  </div>
                </div>
                <div>
                  <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 block">Text</label>
                  <div className="flex gap-2">
                    <input
                      type="color"
                      value={textColor}
                      onChange={(e) => setTextColor(e.target.value)}
                      className="w-12 h-12 rounded-lg cursor-pointer border-2 border-gray-300 dark:border-gray-600 shrink-0"
                    />
                    <input
                      type="text"
                      value={textColor}
                      onChange={(e) => setTextColor(e.target.value)}
                      className="flex-1 min-w-0 bg-gray-50 dark:bg-gray-800 border-2 border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 text-xs font-mono text-black dark:text-white outline-none focus:border-neon-green"
                    />
                  </div>
                </div>
              </div>
              {/* Preset Colors */}
              <div>
                <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 block">Color Presets</label>
                <div className="grid grid-cols-4 gap-2">
                  <button
                    onClick={() => {
                      setPrimaryColor('#7C3AED');
                      setSecondaryColor('#14F195');
                      setTextColor('#FFFFFF');
                    }}
                    className="h-12 rounded-lg border-2 border-gray-300 dark:border-gray-600"
                    style={{ background: 'linear-gradient(135deg, #7C3AED 0%, #14F195 100%)' }}
                    title="Purple & Green"
                  />
                  <button
                    onClick={() => {
                      setPrimaryColor('#FF6B6B');
                      setSecondaryColor('#FFD93D');
                      setTextColor('#FFFFFF');
                    }}
                    className="h-12 rounded-lg border-2 border-gray-300 dark:border-gray-600"
                    style={{ background: 'linear-gradient(135deg, #FF6B6B 0%, #FFD93D 100%)' }}
                    title="Red & Yellow"
                  />
                  <button
                    onClick={() => {
                      setPrimaryColor('#4FACFE');
                      setSecondaryColor('#00F2FE');
                      setTextColor('#FFFFFF');
                    }}
                    className="h-12 rounded-lg border-2 border-gray-300 dark:border-gray-600"
                    style={{ background: 'linear-gradient(135deg, #4FACFE 0%, #00F2FE 100%)' }}
                    title="Blue Gradient"
                  />
                  <button
                    onClick={() => {
                      setPrimaryColor('#A8E6CF');
                      setSecondaryColor('#DCEDC1');
                      setTextColor('#2C3E50');
                    }}
                    className="h-12 rounded-lg border-2 border-gray-300 dark:border-gray-600"
                    style={{ background: 'linear-gradient(135deg, #A8E6CF 0%, #DCEDC1 100%)' }}
                    title="Mint & Cream"
                  />
                </div>
              </div>
            </div>
          </div>
        )}

        <div className="h-10"></div>

        {/* Generate Button - Fixed at bottom */}
        <div className="flex gap-3 fixed z-10 bottom-20 left-0 right-0 max-w-lg mx-auto px-6">
          <button
            onClick={async () => {
              const newLinkId = generateLinkId();
              setLinkId(newLinkId);
              if (activeMode === 'blink') {
                saveBlinkCard(newLinkId);
              }
              // For P-link, we'll generate the card image after dialog opens
              // The image will be generated in useEffect when link is set
            }}
            disabled={savingCard || generatingImage}
            className="w-full bg-neon-green hover:bg-green-400 active:bg-green-500 text-black font-bold text-lg py-4 rounded-xl shadow-lg shadow-green-500/20 transition-all transform active:scale-[0.98] flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <span>{savingCard ? 'Saving...' : generatingImage ? 'Generating...' : `Generate ${activeMode === 'plink' ? 'P-Link' : 'Blink'}`}</span>
            <span className="text-xl">→</span>
          </button>
        </div>
      </main>

      {/* Success Dialog */}
      <AnimatePresence>
        {link && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => {
                setLinkId(null);
                setSelectedImage(null);
                setImagePreview(null);
                setIsAutoGeneratedImage(false);
              }}
              className="fixed inset-0 bg-black/40 backdrop-blur-sm z-40"
            />
            <motion.div
              initial={{ y: '100%' }}
              animate={{ y: 0 }}
              exit={{ y: '100%' }}
              transition={{ type: 'spring', damping: 30, stiffness: 300 }}
              className="fixed bottom-15 left-0 right-0 bg-white dark:bg-gray-950 rounded-t-3xl z-50 max-h-[80vh] flex flex-col"
            >
              <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
                <h3 className="text-xl font-bold text-black dark:text-white">{activeMode === 'plink' ? 'P-Link' : 'Blink'} Generated!</h3>
                <button
                  onClick={() => {
                    setLinkId(null);
                    setSelectedImage(null);
                    setImagePreview(null);
                    setIsAutoGeneratedImage(false);
                  }}
                  className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                >
                  <X className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                </button>
              </div>
              <div className="p-6 overflow-y-auto">
                <div className="space-y-4">
                  {/* Amount Summary - Phantom Card Theme */}
                  <div
                    ref={requestingCardRef}
                    className="relative rounded-xl bg-linear-to-br from-gray-900 to-black dark:from-black dark:to-gray-950 border border-solana-purple/60 p-6 overflow-hidden shadow-lg shadow-solana-purple/20"
                  >
                    {/* Solana Logo Background */}
                    <div className="absolute inset-0 flex items-center justify-center opacity-10">
                      <NextImage
                        src="/solana-sol-logo.svg"
                        alt="Solana Logo"
                        width={150}
                        height={150}
                        className="object-contain"
                      />
                    </div>

                    {/* Background Blur Effects */}
                    <div className="absolute -left-10 top-0 w-40 h-40 bg-solana-purple/40 blur-[60px] rounded-full"></div>
                    <div className="absolute -right-10 bottom-0 w-48 h-48 bg-neon-green/30 blur-[70px] rounded-full"></div>

                    {/* Content */}
                    <div className="relative z-10 text-center">
                      <p className="text-sm text-gray-400 mb-3 font-mono tracking-wide">REQUESTING</p>
                      <div className="flex items-baseline justify-center gap-3">
                        <span className="text-5xl font-bold text-white drop-shadow-[0_0_10px_rgba(19,241,149,0.4)] tracking-tight">{requestedAmount}</span>
                        <span className="text-2xl text-neon-green font-bold tracking-wider drop-shadow-[0_0_8px_rgba(19,241,149,0.5)]">SOL</span>
                      </div>
                      <p className="text-xs text-gray-500 mt-3 font-mono">≈ ${(parseFloat(requestedAmount || '0') * 150).toFixed(2)} USD</p>
                    </div>
                  </div>

                  {/* Link Display */}
                  <div className="bg-gray-50 dark:bg-gray-900 rounded-xl p-4 border border-gray-200 dark:border-gray-700">
                    <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-2">Payment Link</p>
                    <p className="text-xs font-mono text-black dark:text-white break-all bg-white dark:bg-gray-800 p-3 rounded-lg border border-gray-200 dark:border-gray-600">
                      {link}
                    </p>
                  </div>

                  {/* Info Box */}
                  <div className="bg-purple-50 dark:bg-purple-950/20 rounded-xl p-4 border border-purple-200 dark:border-purple-900">
                    <p className="text-xs font-semibold text-purple-900 dark:text-purple-200 mb-2 flex items-center gap-1">
                      <Info className="w-4 h-4" />
                      {activeMode === 'plink' ? 'How to use' : 'Share on social media'}
                    </p>
                    <p className="text-xs text-purple-800 dark:text-purple-300">
                      {activeMode === 'plink'
                        ? 'Share this link with the payer. They will generate a secret during deposit and share it with you privately for claiming.'
                        : 'Post this link on Twitter, Discord, or any platform. Users can pay directly from the post if they have a Solana wallet extension.'}
                    </p>
                  </div>

                  {/* Custom Message Section */}
                  <div className="bg-gray-50 dark:bg-gray-900 rounded-xl p-4 border border-gray-200 dark:border-gray-700">
                    <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-2">Add Personal Message (Optional)</p>
                    <textarea
                      value={customMessage}
                      onChange={(e) => setCustomMessage(e.target.value)}
                      placeholder={`Add a personal note... (Payment details and link will be included automatically)`}
                      className="w-full bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg px-3 py-2 text-sm text-black dark:text-white placeholder:text-gray-400 dark:placeholder:text-gray-500 outline-none focus:border-neon-green transition-colors resize-none"
                      rows={3}
                    />
                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
                      Payment details, link, and website info will be automatically added below your message
                    </p>
                  </div>

                  {/* Image Upload Section */}
                  <div className="bg-gray-50 dark:bg-gray-900 rounded-xl p-4 border border-gray-200 dark:border-gray-700">
                    <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-2">Add Image (Optional)</p>
                    <div className="flex gap-3">
                      {imagePreview ? (
                        <div className="relative">
                          <img src={imagePreview} alt="Preview" className="w-20 h-20 object-cover rounded-lg" />
                          <button
                            onClick={() => {
                              setSelectedImage(null);
                              setImagePreview(null);
                            }}
                            className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full w-5 h-5 flex items-center justify-center text-xs"
                          >
                            ×
                          </button>
                        </div>
                      ) : (
                        <label className="flex items-center justify-center w-20 h-20 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg cursor-pointer hover:border-neon-green transition-colors">
                          <input
                            type="file"
                            accept="image/*"
                            onChange={handleImageSelect}
                            className="hidden"
                          />
                          <Image size={24} className="text-gray-400" />
                        </label>
                      )}
                      <div className="flex-1 flex items-center">
                        <p className="text-xs text-gray-500 dark:text-gray-400">
                          {imagePreview ? 'Image attached for sharing' : 'Add an image to share with your payment link'}
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Action Buttons */}
                  <div className="flex gap-3 pt-2">
                    <button
                      onClick={() => {
                        setLinkId(null);
                        setSelectedImage(null);
                        setImagePreview(null);
                        setIsAutoGeneratedImage(false);
                      }}
                      className="flex-1 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-black dark:text-white font-semibold py-3 rounded-xl transition-colors"
                    >
                      Close
                    </button>
                    {typeof navigator !== 'undefined' && 'share' in navigator && (
                      <button
                        onClick={handleShare}
                        className="flex-1 bg-purple-500 hover:bg-purple-600 text-white font-bold py-3 rounded-xl shadow-lg transition-all flex items-center justify-center gap-2"
                      >
                        <Share2 size={20} />
                        Share
                      </button>
                    )}
                    <button
                      onClick={handleCopy}
                      className="flex-1 bg-neon-green hover:bg-green-400 active:bg-green-500 text-black font-bold py-3 rounded-xl shadow-lg shadow-green-500/20 transition-all transform active:scale-[0.98] flex items-center justify-center gap-2"
                    >
                      {copied ? (
                        <>
                          <Check size={20} />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy size={20} />
                          Copy
                        </>
                      )}
                    </button>
                  </div>
                </div>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* How it works dialog */}
      <AnimatePresence>
        {showHowItWorks && (
          <>
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowHowItWorks(false)}
              className="fixed inset-0 bg-black/50 backdrop-blur-sm z-40"
            />

            {/* Dialog */}
            <motion.div
              initial={{ y: "100%" }}
              animate={{ y: 0 }}
              exit={{ y: "100%" }}
              transition={{ type: "spring", damping: 30, stiffness: 300 }}
              className="fixed bottom-0 left-0 right-0 bg-white dark:bg-gray-950 rounded-t-3xl shadow-2xl z-50 max-h-[80vh] overflow-y-auto hide-scrollbar"
              style={{
                scrollbarWidth: "none",
                msOverflowStyle: "none"
              }}
            >
              <div className="sticky top-0 bg-white dark:bg-gray-950 border-b border-gray-200 dark:border-gray-800 px-6 py-4 flex items-center justify-between">
                <h3 className="font-bold text-lg text-black dark:text-white">How {activeMode === 'plink' ? 'P-Links' : 'Blinks'} Work</h3>
                <button
                  onClick={() => setShowHowItWorks(false)}
                  className="p-2 hover:bg-gray-100 dark:hover:bg-gray-900 rounded-lg transition-colors"
                >
                  <X size={20} className="text-gray-500 dark:text-gray-400" />
                </button>
              </div>

              <div className="p-6 pb-20">
                {activeMode === 'plink' ? (
                  // P-Link content
                  <>
                    <div className="bg-neon-green/10 dark:bg-neon-green/20 border border-neon-green/30 rounded-2xl p-5 mb-6">
                      <div className="flex items-center gap-2 mb-2">
                        <Lock size={16} className="text-neon-green" />
                        <span className="text-sm font-bold text-black dark:text-white">Zero-Knowledge Privacy</span>
                      </div>
                      <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed">
                        P-Links use zero-knowledge proofs to keep your transactions completely private. Your wallet address is never exposed to the other party.
                      </p>
                    </div>

                    <ul className="space-y-4 text-sm text-gray-600 dark:text-gray-400">
                      <li className="flex gap-3">
                        <div className="shrink-0 w-8 h-8 rounded-full bg-neon-green/20 flex items-center justify-center">
                          <span className="text-neon-green font-bold text-sm">1</span>
                        </div>
                        <div>
                          <strong className="text-black dark:text-white block mb-1">Recipient Creates Request</strong>
                          <span className="text-xs">The recipient creates a payment request specifying the amount needed and generates a shareable link.</span>
                        </div>
                      </li>

                      <li className="flex gap-3">
                        <div className="shrink-0 w-8 h-8 rounded-full bg-neon-green/20 flex items-center justify-center">
                          <span className="text-neon-green font-bold text-sm">2</span>
                        </div>
                        <div>
                          <strong className="text-black dark:text-white block mb-1">Payer Deposits Funds</strong>
                          <span className="text-xs">The payer uses the link to deposit funds using zero-knowledge proofs. They receive a unique secret after deposit.</span>
                        </div>
                      </li>

                      <li className="flex gap-3">
                        <div className="shrink-0 w-8 h-8 rounded-full bg-neon-green/20 flex items-center justify-center">
                          <span className="text-neon-green font-bold text-sm">3</span>
                        </div>
                        <div>
                          <strong className="text-black dark:text-white block mb-1">Secret Shared Privately</strong>
                          <span className="text-xs">The payer shares the secret privately with the recipient through any secure channel (encrypted message, in person, etc.).</span>
                        </div>
                      </li>

                      <li className="flex gap-3">
                        <div className="shrink-0 w-8 h-8 rounded-full bg-neon-green/20 flex items-center justify-center">
                          <span className="text-neon-green font-bold text-sm">4</span>
                        </div>
                        <div>
                          <strong className="text-black dark:text-white block mb-1">Recipient Claims Payment</strong>
                          <span className="text-xs">The recipient uses the secret to claim the funds to any wallet address. The payer's identity remains completely private.</span>
                        </div>
                      </li>
                    </ul>

                    <div className="mt-6 pt-6 border-t border-gray-200 dark:border-gray-800">
                      <div className="flex items-start gap-2 text-xs text-gray-600 dark:text-gray-400">
                        <span className="text-lg">🔒</span>
                        <span className="leading-relaxed">
                          <strong className="text-black dark:text-white">Privacy Guaranteed:</strong> Zero-knowledge proofs ensure that no one can trace the payment back to your wallet. Your financial privacy is protected at every step.
                        </span>
                      </div>
                    </div>
                  </>
                ) : (
                  // Blink content
                  <>
                    <div className="bg-neon-green/10 dark:bg-neon-green/20 border border-neon-green/30 rounded-2xl p-5 mb-6">
                      <div className="flex items-center gap-2 mb-2">
                        <Share2 size={16} className="text-neon-green" />
                        <span className="text-sm font-bold text-black dark:text-white">Social Media Payments</span>
                      </div>
                      <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed">
                        Blinks allow users to pay directly from social media platforms. Share your payment link on Twitter, Discord, or any platform and receive payments seamlessly.
                      </p>
                    </div>

                    <ul className="space-y-4 text-sm text-gray-600 dark:text-gray-400">
                      <li className="flex gap-3">
                        <div className="shrink-0 w-8 h-8 rounded-full bg-neon-green/20 flex items-center justify-center">
                          <span className="text-neon-green font-bold text-sm">1</span>
                        </div>
                        <div>
                          <strong className="text-black dark:text-white block mb-1">Create Blink</strong>
                          <span className="text-xs">Create a payment link (Blink) with the requested amount and copy it to share.</span>
                        </div>
                      </li>

                      <li className="flex gap-3">
                        <div className="shrink-0 w-8 h-8 rounded-full bg-neon-green/20 flex items-center justify-center">
                          <span className="text-neon-green font-bold text-sm">2</span>
                        </div>
                        <div>
                          <strong className="text-black dark:text-white block mb-1">Share on Social Media</strong>
                          <span className="text-xs">Post the link on Twitter, Discord, Telegram, or any social platform where you want to receive payments.</span>
                        </div>
                      </li>

                      <li className="flex gap-3">
                        <div className="shrink-0 w-8 h-8 rounded-full bg-neon-green/20 flex items-center justify-center">
                          <span className="text-neon-green font-bold text-sm">3</span>
                        </div>
                        <div>
                          <strong className="text-black dark:text-white block mb-1">Payer Clicks Link</strong>
                          <span className="text-xs">If the payer has a Solana browser extension installed, an interactive payment card appears directly in the social media post. Otherwise, they see a preview image with a redirect button.</span>
                        </div>
                      </li>

                      <li className="flex gap-3">
                        <div className="shrink-0 w-8 h-8 rounded-full bg-neon-green/20 flex items-center justify-center">
                          <span className="text-neon-green font-bold text-sm">4</span>
                        </div>
                        <div>
                          <strong className="text-black dark:text-white block mb-1">Payment Completed</strong>
                          <span className="text-xs">The payer completes the payment directly from the social media platform using their wallet extension, or gets redirected to complete the payment.</span>
                        </div>
                      </li>
                    </ul>

                    <div className="mt-6 pt-6 border-t border-gray-200 dark:border-gray-800">
                      <div className="flex items-start gap-2 text-xs text-gray-600 dark:text-gray-400">
                        <span className="text-lg">⚡</span>
                        <span className="leading-relaxed">
                          <strong className="text-black dark:text-white">Instant & Seamless:</strong> Blinks make crypto payments as easy as clicking a link. No need to leave your favorite social platform to send or receive payments.
                        </span>
                      </div>
                    </div>
                  </>
                )}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
